# metadata
# 	title = Downmix Audio To Stereo 
# 	description = Downmixes all audio to stereo, may improve playback.
# 	author = hexa0
# 	defaultEnabled = false
# end

audio-channels=stereo
ad-lavc-downmix=yes