# metadata
# 	title = Semitone Pitch Controls
# 	description = Shifts pitch by 1 semitone instead when using pitch binds.
# 	author = hexa0
# end

[ multiply speed 0.9438743126816935
] multiply speed 1.059463094352953